# Generated by Django 5.0.6 on 2024-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admintbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=255)),
                ('adminemail', models.EmailField(max_length=254)),
                ('adminpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
