# Generated by Django 5.0.6 on 2024-08-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
        ('wardenapp', '0002_alter_roomtbl_wardenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstbl',
            name='roomID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='wardenapp.roomtbl'),
        ),
    ]
