# Generated by Django 5.0.6 on 2024-08-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentstbl_roomid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstbl',
            old_name='roomID',
            new_name='roomOBJ',
        ),
    ]
