# Generated by Django 5.0.6 on 2024-08-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteltbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=255)),
                ('hphone', models.IntegerField()),
                ('hemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Wardentbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=255)),
                ('wplace', models.CharField(max_length=255)),
                ('wage', models.IntegerField()),
                ('wphone', models.IntegerField()),
                ('wemail', models.EmailField(max_length=254)),
                ('wpassword', models.CharField(max_length=255)),
                ('wapproval', models.BooleanField(default=False)),
                ('approval_request_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roomtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('students_count', models.IntegerField(choices=[(1, '1 Student'), (2, '2 Students'), (3, '3 Students')], default=1)),
                ('beds_count', models.IntegerField(choices=[(1, '1 Bed'), (2, '2 Beds'), (3, '3 Beds')], default=1)),
                ('room_photo', models.FileField(null=True, upload_to='roomphotos')),
                ('students_current_count', models.IntegerField(default=0, null=True)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wardenapp.hosteltbl')),
                ('wardenID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wardenapp.wardentbl')),
            ],
        ),
    ]
