# Generated by Django 5.0.6 on 2024-08-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtbl',
            name='wardenID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wardenapp.wardentbl'),
        ),
    ]
