# Generated by Django 5.0.6 on 2024-08-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0002_alter_roomtbl_wardenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtbl',
            name='room_status',
            field=models.CharField(choices=[('fully', 'Fully Occupied'), ('partial', 'Partially Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=100),
        ),
    ]
