# Generated by Django 5.0.6 on 2024-08-23 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0003_roomtbl_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtbl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomtbl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
