# Generated by Django 5.0.6 on 2024-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0005_breakfasttbl_dinnertbl_lunchtbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplantbl',
            name='breakfastOBJS',
        ),
        migrations.RemoveField(
            model_name='mealplantbl',
            name='dinnerOBJS',
        ),
        migrations.RemoveField(
            model_name='mealplantbl',
            name='lunchOBJS',
        ),
    ]
