# Generated by Django 5.0.6 on 2024-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0006_remove_mealplantbl_breakfastobjs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplantbl',
            name='breakfastOBJS',
            field=models.ManyToManyField(related_name='breakfastobjs', to='wardenapp.breakfasttbl'),
        ),
        migrations.AddField(
            model_name='mealplantbl',
            name='dinnerOBJS',
            field=models.ManyToManyField(related_name='dinnerobjs', to='wardenapp.dinnertbl'),
        ),
        migrations.AddField(
            model_name='mealplantbl',
            name='lunchOBJS',
            field=models.ManyToManyField(related_name='lunchobjs', to='wardenapp.lunchtbl'),
        ),
    ]
