# Generated by Django 5.0.6 on 2024-09-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0007_mealplantbl_breakfastobjs_mealplantbl_dinnerobjs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mealplantbl',
            new_name='ScheduledMealdtbl',
        ),
    ]
