# Generated by Django 5.0.6 on 2024-09-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0008_rename_mealplantbl_scheduledmealdtbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmealdtbl',
            name='mealapprovel',
            field=models.BooleanField(default=False),
        ),
    ]
