# Generated by Django 5.0.6 on 2024-09-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0009_scheduledmealdtbl_mealapprovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedmealtbl',
            name='plannedmealOBJ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannedmealobj', to='wardenapp.scheduledmealdtbl'),
        ),
    ]
