# Generated by Django 5.0.6 on 2024-09-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0010_alter_selectedmealtbl_plannedmealobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedmealtbl',
            name='breakfastOBJ',
        ),
        migrations.RemoveField(
            model_name='selectedmealtbl',
            name='dinnerOBJ',
        ),
        migrations.RemoveField(
            model_name='selectedmealtbl',
            name='lunchOBJ',
        ),
    ]
