# Generated by Django 5.0.6 on 2024-09-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0011_remove_selectedmealtbl_breakfastobj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedmealtbl',
            name='breakfastOBJ',
            field=models.ManyToManyField(related_name='breakfastobj', to='wardenapp.breakfasttbl'),
        ),
        migrations.AddField(
            model_name='selectedmealtbl',
            name='dinnerOBJ',
            field=models.ManyToManyField(related_name='dinnerobj', to='wardenapp.dinnertbl'),
        ),
        migrations.AddField(
            model_name='selectedmealtbl',
            name='lunchOBJ',
            field=models.ManyToManyField(related_name='lunchobj', to='wardenapp.lunchtbl'),
        ),
    ]
