# Generated by Django 5.0.6 on 2024-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardenapp', '0013_selectedmealtbl_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedmealtbl',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
