# Generated by Django 5.0.6 on 2024-09-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_roomid_studentstbl_roomobj'),
        ('wardenapp', '0014_selectedmealtbl_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_bill_generated', to='wardenapp.wardentbl')),
                ('studentOBJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='studentapp.studentstbl')),
            ],
        ),
    ]
