# Generated by Django 5.0.6 on 2024-09-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_roomid_studentstbl_roomobj'),
        ('wardenapp', '0015_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='Billtbl',
        ),
    ]
